### ISSUE TITLE
Would you have a demo for this admin header?

### ISSUE THREAD

**Issue by topstarnetwork** [Zookal/Magento-AdminHeaderTheme#1]
Would you have a demo for this admin header?
Regards, Heather

**Comment by SchumacherFM** [comment]
OMG sorry for the delay and yes here is the demo:

![Config](https://raw.githubusercontent.com/Zookal/Magento-AdminHeaderTheme/master/printscreens/config.png)

![development](https://raw.githubusercontent.com/Zookal/Magento-AdminHeaderTheme/master/printscreens/env_dev.png)

![staging](https://raw.githubusercontent.com/Zookal/Magento-AdminHeaderTheme/master/printscreens/env_staging.png)

![production](https://raw.githubusercontent.com/Zookal/Magento-AdminHeaderTheme/master/printscreens/env_prod.png)
